// SPDX-License-Identifier: MIT

pragma solidity 0.8.34;

import "forge-std/Test.sol";

import "../src/Calculadora.sol";

contract CalculadoraTest is Test {
    
    Calculadora calculadora;
    address admin = vm.addr(1);
    address randomUser = vm.addr(2);
    uint256 firstResult = 100;

    function setUp() public {
        calculadora = new Calculadora(100, admin);
    }

    // Unit testing
    function testCheckFirstResult() public view {
        uint256 firstResult_ = calculadora.result();
        assert(firstResult_ == firstResult);
    }

    function testAddition() public {
        uint256 num1_ = 5;
        uint256 num2_ = 5;

        uint256 result_ = calculadora.addition(num1_, num2_);
        assert(result_ == num1_ + num2_);
    }

    function testSubstract() public {
        uint256 num1_ = 5;
        uint256 num2_ = 5;

        uint256 result_ = calculadora.substract(num1_, num2_);
        assert(result_ == num1_ - num2_);
    }

    function testMultiplier() public {
        uint256 num1_ = 5;
        uint256 num2_ = 5;

        uint256 result_ = calculadora.multiplier(num1_, num2_);
        assert(result_ == num1_ * num2_);
    }

    function testCannotMulitply2LargeNumbers() public {
        uint256 num1_ = 115792089237316195423570985008687907853269984665640564039457584007913129639933;
        uint256 num2_ = 5;

        vm.expectRevert();
        calculadora.multiplier(num1_, num2_);
    }

    function testIfNotAdminCallsDivisionReverts() public {
        vm.startPrank(randomUser);

        uint256 num1_ = 5;
        uint256 num2_ = 2;
        vm.expectRevert();
        calculadora.division(num1_, num2_);
        
        vm.stopPrank();
    }

    function testAdminCanCallDivisionCorrectly() public {
        vm.startPrank(admin);

        uint256 num1_ = 5;
        uint256 num2_ = 2;
        calculadora.division(num1_, num2_);
        
        vm.stopPrank();
    }

    function testDefaultCannotCallDivisionCorrectly() public {
        uint256 num1_ = 5;
        uint256 num2_ = 2;
        console.log(msg.sender);
        vm.expectRevert();
        calculadora.division(num1_, num2_);
    }

    function testDefaultExecutesCorrectly() public {
        vm.startPrank(admin);

        uint256 num1_ = 5;
        uint256 num2_ = 2;
        uint256 result_ = calculadora.division(num1_, num2_);
        assert(result_ == num1_ / num2_);

        vm.stopPrank();
    }

    function testCannotDivideByZero() public {
        vm.startPrank(admin);

        uint256 num1_ = 5;
        uint256 num2_ = 0;
        vm.expectRevert();
        calculadora.division(num1_, num2_);

        vm.stopPrank();
    }

    // Fuzzing testing => random inputs generated by Foundry

    function testFuzzingDivision(uint256 num1_, uint256 num2_) public {
        vm.startPrank(admin);

        calculadora.division(num1_, num2_);

        vm.stopPrank();
    }
}